### ISSUE TITLE
Vector.dev sink configuration

### ISSUE THREAD

**Issue by saeed-mcu** [manticoresoftware/manticoresearch-buddy#302]
### Bug Description:

I used following  `vector.toml` config file based on [Vector.dev](https://manticoresearch.com/blog/integration-of-manticore-with-vectordev/) document

```toml

[sources.test_file]
type = "file"
include = [ "/root/vector2manticore/dpkg.log" ]

[transforms.modify_test_file]
type = "remap"
inputs = [ "test_file" ]
source = """
.vec_timestamp = del(.timestamp)"""

[sinks.manticor]
type = "elasticsearch"
inputs = [ "modify_test_file" ]
endpoints = ["http://4.4.4.205:9308"]
bulk.index = "dpkg_log"
```
But after run vector , It's failed for Health check
```bash
$ vector validate /root/vector2manticore/vector.toml 
√ Loaded ["/root/vector2manticore/vector.toml"]
√ Component configuration
2024-05-29T10:18:40.813583Z ERROR vector::topology::builder: msg="Healthcheck failed." error=Unexpected status: 404 Not Found component_kind="sink" component_type="elasticsearch" component_id=manticor component_name=manticor
x Health check for "manticor" failed: Unexpected status: 404 Not Found
```
This is docker-compose file for manticore:
```yml
version: "3.5"

services:
  manticore:
    image: manticoresearch/manticore:6.3.0
    network_mode: "host"    

  manticore_exporter:
    image: netgineer/manticore-exporter:latest
    network_mode: "host"

```

### Manticore Search Version:

Manticore 6.3.0 1811a9efb@24052209

### Operating System Version:

Ubuntu 22.04 

### Have you tried the latest development version?

- [X] Yes

### Internal Checklist:

<sup>To be completed by the assignee. Check off tasks that have been completed or are not applicable.</sup>
<details>

- [ ] Task estimated
- [ ] Specification created, reviewed, and approved
- [ ] Implementation completed
- [ ] Tests developed
- [ ] Documentation updated
- [ ] Documentation proofread
- [ ] Changelog updated

</details>
